CREATE DATABASE IF NOT EXISTS DE_TUTORIAL;
USE DATABASE DE_TUTORIAL;
CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID INT,
    NAME STRING,
    JOIN_DATE DATE
);

CREATE STAGE IF NOT EXISTS INGEST_STAGE;
