name: Snowflake CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"

      - name: Configure Snowflake CLI
        run: |
          mkdir -p ~/.snowflake
          cat << EOF > ~/.snowflake/config.toml
          [connections.default]
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USER }}"
          password = "${{ secrets.SF_PASSWORD }}"
          role = "ACCOUNTADMIN"
          warehouse = "SNOWFLAKE_LEARNING_WH"
          database = "DE_TUTORIAL"
          schema = "RAW"
          EOF
          chmod 0600 ~/.snowflake/config.toml

      - name: Execute Infrastructure Setup
        run: snow sql -f setup.sql

      - name: Build and Deploy Snowpark App
        run: |
          cd snowpark_demo
          snow snowpark build
          snow snowpark deploy --replace
